apiVersion: v1
data:
  oidc.ca-pem: "{{ b64enc .Values.oidc.caPEM }}"
  oidc.issuer-url: {{ b64enc .Values.oidc.issuerUrl }}
  oidc.username-claim: {{ b64enc .Values.oidc.usernameClaim }}
  oidc.client-id: {{ b64enc .Values.oidc.clientId }}
kind: Secret
metadata:
  name: {{ include "kube-oidc-proxy.fullname" . }}-config
  labels:
{{ include "kube-oidc-proxy.labels" . | indent 4 }}
type: Opaque